import streamlit as st
import yfinance as yf
import pandas_ta as ta
import google.generativeai as genai
import json

# 1. Setup API
genai.configure(api_key="YOUR_GEMINI_API_KEY")

def get_ai_analysis(rsi, adx, close):
    model = genai.GenerativeModel('gemini-1.5-flash')
    prompt = f"""
    Analyze these Forex indicators: Price={close}, RSI={rsi:.2f}, ADX={adx:.2f}.
    Provide a signal (BUY, SELL, or WAIT) and a Confidence Score (0-100%).
    Return ONLY a JSON object:
    {{"signal": "BUY", "confidence": 85, "reason": "Strong trend with RSI support"}}
    """
    try:
        response = model.generate_content(prompt)
        # Clean response text in case AI adds markdown code blocks
        clean_json = response.text.replace("```json", "").replace("```", "").strip()
        return json.loads(clean_json)
    except Exception as e:
        return {"signal": "ERROR", "confidence": 0, "reason": str(e)}

# 2. Streamlit UI
st.set_page_config(page_title="Gemini FX Pro", layout="wide")
st.title("🤖 Gemini AI Market Analyst")

ticker = st.text_input("Enter Ticker (e.g., EURUSD=X)", value="EURUSD=X")

if st.button("Generate Signal"):
    # Download data
    data = yf.download(ticker, period="1d", interval="15m")
    
    if not data.empty:
        # --- FIX: Flatten Multi-Index Columns (The most common error) ---
        if isinstance(data.columns, pd.MultiIndex):
            data.columns = data.columns.get_level_values(0)
            
        # Calculate Indicators
        data['RSI'] = ta.rsi(data['Close'], length=14)
        adx_df = ta.adx(data['High'], data['Low'], data['Close'], length=14)
        
        # Combine ADX result into main dataframe
        data = pd.concat([data, adx_df], axis=1)
        
        # Get latest values
        last_row = data.iloc[-1]
        # Use exact column names generated by pandas_ta
        rsi_val = last_row['RSI']
        adx_val = last_row['ADX_14']
        price = last_row['Close']

        # AI Analysis
        with st.spinner("Analyzing market structure..."):
            result = get_ai_analysis(rsi_val, adx_val, price)

        # 3. Display Results
        col1, col2, col3 = st.columns(3)
        col1.metric("Price", f"{price:.4f}")
        col2.metric("RSI", f"{rsi_val:.2f}")
        col3.metric("ADX (Trend Strength)", f"{adx_val:.2f}")

        st.divider()

        # Signal Box
        sig = result['signal']
        conf = result['confidence']
        
        if sig == "BUY":
            st.success(f"### 🚀 SIGNAL: {sig} ({conf}%)")
        elif sig == "SELL":
            st.error(f"### 📉 SIGNAL: {sig} ({conf}%)")
        else:
            st.warning(f"### ⚖️ SIGNAL: {sig} ({conf}%)")
            
        st.info(f"**AI Reason:** {result['reason']}")
    else:
        st.error("Could not fetch data. Check ticker name.")
